### ISSUE TITLE
exception after reload

### ISSUE THREAD

**Issue by 7henry767** [Janhektor/Community#50]
Trace:

[20:22:06 ERROR]: Error occurred while enabling Community v0.0.1 (Is it up to da
te?)
java.util.MissingResourceException: Can't find bundle for base name resources.st
rings, locale en
        at java.util.ResourceBundle.throwMissingResourceException(Unknown Source
) ~[?:1.8.0_45]
        at java.util.ResourceBundle.getBundleImpl(Unknown Source) ~[?:1.8.0_45]
        at java.util.ResourceBundle.getBundle(Unknown Source) ~[?:1.8.0_45]
        at de.janhektor.community.Main.onEnable(Main.java:56) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[s
pigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:340) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:405) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.jav
a:356) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.
java:316) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:74
2) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigot-1.8.7.jar:git-Spigo
t-6d0ae89-a03743b]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:
25) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServe
r.java:642) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(Craf
tServer.java:628) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:
404) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
68) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
57) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:560) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]

**Comment by Janhektor** [comment]
Thanks for reporting this error.

We already saw this stacktrace - if you try to restart (not reload) your server, it'll work fine.
I've tried to use <b>ResourceBundle#clearCache</b> in onDisable, but it doesn't work.
This issue is still open - good idea to create a public report on GitHub.
We'll try to find a solution.

Janhektor
