### ISSUE TITLE
NullPointerException at PlayerJoinEvent 

### ISSUE THREAD

**Issue by 7henry767** [Janhektor/Community#51]
trace:

[20:26:09 ERROR]: Could not pass event PlayerJoinEvent to Community v0.0.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:310) ~[spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:
296) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:156) [spigo
t-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [
spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231
) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java
:148) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:8
17) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
67) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
57) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:560) [spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
        at de.janhektor.community.achievements.AchievementManager.loadAchievemen
ts(AchievementManager.java:41) ~[?:?]
        at de.janhektor.community.achievements.AchievementJoinListener.onJoin(Ac
hievementJoinListener.java:11) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[spigot-1.8.7.jar:git-Spigot-6d0ae89-a03743b]
        ... 14 more

**Comment by Janhektor** [comment]
This error is caused by the missing AchievementDataManager.
It'll be automatically fixed when we've initialized the field in our main class with an implementation.
But thank you for reporting - every stacktrace useful for improvisation.
